#! /bin/bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

leftwm-command "LoadTheme" $SCRIPTPATH/theme.ron

# Bar
eww -c $SCRIPTPATH/eww/bar open bar

# App launcher
ulauncher&

# Screenshots
flameshot&

# Clipboard manager
clipit&

# Compositor
picom --experimental-backends -b
flashfocus&

# Wallpaper
nitrogen --restore
